server:
  port: 8000

spring:
  cloud:
    gateway:
      routes:
        - id: s3_static_resources
          uri: 'https://opms-assets.s3.ap-southeast-1.amazonaws.com'
          predicates:
            - Path=/s3/**
        - id: react_website
          uri: 'https://opms-dashboard.s3.ap-southeast-1.amazonaws.com'
          predicates:
            - Path=/app/**